Insert into PORTAL_USER (USER_NAME,PASSWORD,ENABLED) values ('sarsovsk','$2a$10$qbQZX5zs9ZDICrAgbB0yVOCfoRgQ2O8xyMq/vHrT7BEQD8HOEmZhW', 1);
Insert into PORTAL_USER_ROLES (USER_ROLE_ID,USER_NAME,ROLE) values (1,'sarsovsk','ROLE_USER');

INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10000, 'Pikachu', 'Electric', '#ffff00');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10001, 'Magby', 'Fire', '#ff0000');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10002, 'Buzzwole', 'Fighting', '#ff0000');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10003, 'Gloom', 'Poison', '#0000ff');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10004, 'Larvitar', 'Ground', '#ffff00');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10005, 'Yamask', 'Ghost', '#ffffff');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10006, 'Raichu', 'Electric', '#ffff00');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10007, 'Venonat', 'Bug', '#800080');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10008, 'Jangmo-o', 'Dragon', '#808080');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10009, 'Volcarona', 'Fire', '#ffffff');
INSERT INTO POKEMON (ID, NAME, TYPE, COLOR) VALUES (10010, 'Slowking', 'Fire', '#ffc0cb');